services:
  user-db:
    image: postgres:15-alpine
    container_name: user_db_container
    environment:
      POSTGRES_USER: mario
      POSTGRES_PASSWORD: guerrera
      POSTGRES_DB: user_db
    volumes:
      - ./init_user_db.sql:/docker-entrypoint-initdb.d/init.sql #chiama il file per creare le tabelle
    ports:
      - "5433:5432" #porta per collegarsi al db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mario -d user_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
  data-db:
    image: postgres:15-alpine
    container_name: data_db_container
    environment:
      POSTGRES_USER: mario
      POSTGRES_PASSWORD: guerrera
      POSTGRES_DB: data_db
    volumes:
      - ./init_data_db.sql:/docker-entrypoint-initdb.d/init.sql #chiama il file per creare le tabelle
    ports:
      - "5434:5432" #porta per collegarsi al db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mario -d data_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
  datacollector:
    build: ./datacollector
    container_name: datacollectorcontainer
    depends_on:
      data-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://mario:guerrera@data-db:5432/data_db
      GRPC_USER_MANAGER_HOST: user-manager:50051
      USERNAME_API: ${username}
      PASSWORD_API: ${password}
      GRPC_PORT: 50051
      PERIODO: 10
      KAFKA_HOST: kafka:9092
      KAFKA_TOPIC_ALERT: to-alert-system
  usermanager:
    build: ./usermanager
    container_name: usermanagercontainer
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://mario:guerrera@user-db:5432/user_db
      GRPC_PORT: 50051
      PERIODO: 10
  nginx:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: apigateway
    ports:
      - "80:80" #porta esterna
    volumes:
      - ./nginx/configs/routing.conf:/etc/nginx/conf.d/routing.conf
    depends_on:
      usermanager:
        condition: service_started
      datacollector:
        condition: service_started
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      CLUSTER_ID: x5cg3q9LSQa0hMh5gtbm4w
      KAFKA_CLUSTER_ID: x5cg3q9LSQa0hMh5gtbm4w
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
  alertsystem:
    build: ./alertsystem
    container_name: alertsystemcontainer
    depends_on:
      kafka:
        condition: service_started
      datacollector:
        condition: service_started
    environment:
      KAFKA_HOST: kafka:9092
      TOPIC_IN: to-alert-system
      TOPIC_OUT: to-notifier
      DATA_COLLECTOR_HOST: apigate.com
  alertnotifiersystem:
    build: ./alertnotifiersystem
    container_name: alertnotifiersystemcontainer
    depends_on:
      kafka:
        condition: service_started
    environment:
      KAFKA_HOST: kafka:9092
      TOPIC_IN: to-notifier
volumes:
  kafka-data: