apiVersion: v1
kind: Service
metadata:
  name: usermanager
  namespace: homework
spec:
  selector:
    app: usermanager
  ports:
    - name: http
      port: 5000
      targetPort: 5000
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: metrics
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanager
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanager
  template:
    metadata:
      labels:
        app: usermanager
    spec:
      containers:
        - name: usermanager
          image: homework/usermanager:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
            - containerPort: 50051
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://mario:guerrera@user-db:5432/user_db
            - name: GRPC_PORT
              value: "50051"
            - name: PERIODO
              value: "10"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: datacollector
  namespace: homework
spec:
  selector:
    app: datacollector
  ports:
    - name: http
      port: 5000
      targetPort: 5000
    - name: metrics
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacollector
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datacollector
  template:
    metadata:
      labels:
        app: datacollector
    spec:
      containers:
        - name: datacollector
          image: homework/datacollector:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://mario:guerrera@data-db:5432/data_db
            - name: GRPC_PORT
              value: "50051"
            - name: PERIODO
              value: "20"
            - name: KAFKA_BROKER_LIST
              value: kafka:9092
            - name: TOPIC_INPUT_NAME
              value: to-alert-system
            - name: USERNAME_API
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USERNAME_API
            - name: PASSWORD_API
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PASSWORD_API
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
