apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacollector
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datacollector
  template:
    metadata:
      labels:
        app: datacollector
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: datacollector
        image: datacollector:local
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: postgresql://mario:guerrera@data-db:5432/data_db
        - name: GRPC_USER_MANAGER_HOST
          value: usermanager:50051
        - name: USERNAME_API
          valueFrom:
            secretKeyRef:
              name: api-credentials
              key: username
        - name: PASSWORD_API
          valueFrom:
            secretKeyRef:
              name: api-credentials
              key: password
        - name: GRPC_PORT
          value: "50051"
        - name: PERIODO
          value: "100"
        - name: KAFKA_BROKER_LIST
          value: kafka-0.kafka-hs.homework.svc.cluster.local:9092
        - name: TOPIC_INPUT_NAME
          value: to-alert-system
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: http
          containerPort: 5000
        - name: grpc
          containerPort: 50051
        - name: metrics
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: datacollector
  namespace: homework
spec:
  type: ClusterIP
  selector:
    app: datacollector
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  - name: grpc
    port: 50051
    targetPort: 50051
  - name: metrics
    port: 8000
    targetPort: 8000