# kind cluster with port mapping for HTTPS ingress
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: homework
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30443
    hostPort: 443
    protocol: tcp
- role: worker
