apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-routing
  namespace: homework
data:
  routing.conf: |
    server {
        listen 443 ssl;
        server_name apigate.com;
        ssl_certificate     /etc/nginx/ssl/nginx.selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.selfsigned.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        location / {
            return 404 "API Gateway: Endpoint non trovato.";
        }
        location /users {
            proxy_pass http://usermanager:5000/users;
        }
        location /add_user {
            proxy_pass http://usermanager:5000/add_user;
        }
        location /delete_user {
            proxy_pass http://usermanager:5000/delete_user;
        }
        location /flights {
            proxy_pass http://datacollector:5000/flights;
        }
        location /add_interest {
            proxy_pass http://datacollector:5000/add_interest;
        }

        location /add_values{
            proxy_pass http://datacollector:5000/add_values;
        }

        location /interest {
            proxy_pass http://datacollector:5000/interest;
        }
        location ~* /last_flight/([A-Z0-9]+)$ {
            proxy_pass http://datacollector:5000;
        }
        location ~* /average_flights/([A-Z0-9]+)$ {
            proxy_pass http://datacollector:5000;
        }
        location /flights_by_period {
            proxy_pass http://datacollector:5000;
        }
        location ~* /flight_duration/([A-Z0-9]+)$ {
            proxy_pass http://datacollector:5000;
        }

        location /prometheus/ {
            proxy_pass http://prometheus:9090;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_redirect / /prometheus/;
        }

    }
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: homework
spec:
  type: NodePort
  selector:
    app: apigateway
  ports:
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 443
          volumeMounts:
            - name: routing
              mountPath: /etc/nginx/conf.d/routing.conf
              subPath: routing.conf
            - name: tls
              mountPath: /etc/nginx/ssl
      volumes:
        - name: routing
          configMap:
            name: nginx-routing
            items:
              - key: routing.conf
                path: routing.conf
        - name: tls
          secret:
            secretName: apigw-tls
            items:
              - key: nginx.selfsigned.crt
                path: nginx.selfsigned.crt
              - key: nginx.selfsigned.key
                path: nginx.selfsigned.key
