apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-viewer
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-viewer-binding
subjects:
  - kind: ServiceAccount
    name: default       # Il nome del ServiceAccount usato dal tuo pod (visto nei log)
    namespace: homework # Il namespace dove gira il tuo pod
roleRef:
  kind: ClusterRole
  name: prometheus-viewer
  apiGroup: rbac.authorization.k8s.io