apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanager
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manager
  template:
    metadata:
      labels:
        app: user-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: usermanager
        image: usermanager:local
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: postgresql://mario:guerrera@user-db:5432/user_db
        - name: GRPC_PORT
          value: "50051"
        - name: PERIODO
          value: "10"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: http  #VERIFICARE QUESTA COSA
          containerPort: 5000
        - name: grpc
          containerPort: 50051
        - name: metrics
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: usermanager
  namespace: homework
spec:
  type: ClusterIP
  selector:
    app: user-manager
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  - name: grpc
    port: 50051
    targetPort: 50051
  - name: metrics
    port: 8000
    targetPort: 8000